// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddNotesInput struct {
	Name  string `json:"name"`
	Notes string `json:"notes"`
}

type DeletePhotoInput struct {
	Name string `json:"name"`
}

type DownloadPhotoInput struct {
	URL      string  `json:"url"`
	Referrer *string `json:"referrer"`
}

type Photo struct {
	Name    string   `json:"name"`
	Notes   *string  `json:"notes"`
	Tags    []string `json:"tags"`
	Updated int      `json:"updated"`
	Deleted bool     `json:"deleted"`
}

type TagPhotoInput struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

type UploadPhotoInput struct {
	B64data string `json:"b64data"`
}
